[project]
name = "julep-foodie-tour"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "julep>=2.10.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3"
]
